### PR TITLE
Draft: Improve logger implementation

### PR DESCRIPTION
**Pull request by Gadsee**
# Introductory
[Loguru](https://github.com/Delgan/loguru) is a logging framework in python that simplifies and abstracts many of the default logging behavior and requirements.
It has color support, proper time stamps, and log lines by default. It also provides thorough exception tracing.

# Motivation
The previous logging missed a few things, especially the timestamps and line identifiers. This change significantly improves the time taken to debug. While it is possible to add this information into the in-built logging module, it's - in my opinion - subpar to loguru.

This MR is mainly a starting point for discussion, hence the Draft prefix.

# Visual showcase
Code used for the below representation:
```py
    logger.debug("Debug")
    logger.info("Info")
    logger.warning("Warning")
    logger.error("Error")
    logger.critical("Critical")
    try:
        f = 1 / 0
    except ZeroDivisionError as err:
        logger.exception(err)
        return
```
Before:
image

After:
image

# Additional notes
I modified the console mode:
`kernel32.SetConsoleMode(file_handle, 0x0081)`
The mask with 0x0080 disables Ctrl-Keys, so Ctrl+C didn't work with the new implementation since it handles the standard in-/output differently. 0x0001 enables them again, so it's been added.

Should this be a serious consideration for you, I would like to go through the currently logged information and clear up a few of the messages.

### CODE REVIEW

**Review by Kyrluckechuck — COMMENTED** [review]
Thank you for the MR @Gadsee !

I love the enthusiasm of this PR, but it does raise a question to me; what is the major advantage to the switch in logging library compared to [what is already in use](https://github.com/Kyrluckechuck/TFT-Bot/blob/88d5c58a1dcc0ad6b8c99daeaf6f45fd5cf72e51/logging_helper.py#L61)?

I do see the file/module and line number in your second screenshot, and that is possible with the existing library and I just hadn't enabled it since I hadn't needed it so far 😛 

To your additional notes though, that seems very logical to me and I have no issue flipping that bit (whether in this PR or an additional one)!

**Comment by Gadsee** [comment]
Thank you for the review! I've briefly mentioned some advantages in Introductory and Motivation, and I'm happy to get more into the details.

Ease of setup is one of my personal favorites about the library. With standard logging, as you can see in your previous logging setup file, you have to go out of your way to add simple things such as formatting, handlers, file logging, and file retention/logfile rotation. The last point is probably not very relevant to this project. For example, think of the setup for ISO8601 timestamps in logging vs. it being the default in loguru.

Exception handling is another advantage I love about this logger. The traceback is much more detailed and informative than the default traceback. You can also add a `@logger.catch()` annotation to functions; it'll catch anything for you. Useful for functions where we want to log errors but not fail. I've seen a few of those in the project, but I would have to double-check.

One thing worth pointing out that can be argued as an advantage is that logs are sent to stderr instead of stdout by default. This avoids mixing application output (result output) with debug/logging output (diagnostic output) and would encourage making an active decision on which information is required for application output (i.e., end-of-game stats).

Of course, the downsides are adding a new dependency to the project and the potential of the project being abandoned in the future. Also, you can implement all of the above features with logging (with a bit more hassle), so I understand any hesitation or rejection.

**Comment by Kyrluckechuck** [comment]
@Gadsee thanks for the feedback.

To be completely honest, I'm not against the change and the library looks quite versatile, which is nice.

A few things I'd like to see in this MR, though (open to feedback):
-  Add `@logger.catch` before the `main`, `tft_bot_loop`, and `queue` functions, and any others that you might consider 'prone to error' and should not propagate their errors further up (though I think that might be just about all of them)
-  Re-add file logging, but via this library. I'm not against using a rotating "last 10 logs" system, and that might honestly be preferable, which this library looks to make possible. I don't think we should auto-rotate based on file size since the entirety of the specific TFT run may be needed, but each startup should start its own log file
- Ensuring the option to be verbose to console output while always being verbose to file output is respected
- Module/line numbers for logs should not be included in the console output unless verbose mode is enabled

**Comment by Gadsee** [comment]
Hey @Kyrluckechuck, apologies for the late update, but I've only now re-found my motivation to work on the project since a new pass was released :)

As the commit messages already hint, I've implemented the logger formatting, log file retention/rotation, and added `logger.catch` where necessary. Most methods have a `try: ... except Exception: ...` block, so I haven't bothered adding it anywhere else. We/You can consider refactoring this over time, but for now, I'd prefer to have this merged/closed and then move on to supporting Set 8.5 :)

**Comment by Kyrluckechuck** [comment]
> Hey @Kyrluckechuck, apologies for the late update, but I've only now re-found my motivation to work on the project since a new pass was released :)

No worries, to be honest, I am in the same boat and have left this project idle since the last pass had completed 😅 

 
> As the commit messages already hint, I've implemented the logger formatting, log file retention/rotation, and added `logger.catch` where necessary. Most methods have a `try: ... except Exception: ...` block, so I haven't bothered adding it anywhere else. We/You can consider refactoring this over time, but for now, I'd prefer to have this merged/closed and then move on to supporting Set 8.5 :)

This makes sense to me, and I agree it'd be good to get this closed up if possible and iterate on it.

> // EDIT (To prevent posting a comment twice) I have no idea why the commit below changed the **entire** file. Tried to force-push an amend, but that obviously didn't work either. If the above changes are fine, I'll close the PR, drop my forked branch, and will re-add the changes properly.

No worries -- if you don't mind recreating this branch so that it tracks properly (and I can once-over the changes again without mixing up what is already there), that would be greatly appreciated!

**Pull request closed without merging**
