### PR TITLE
Update to Set 9

### PR DESCRIPTION
**Pull request by akshualy**
Set 9

# Description

Updates all the set-specific captures to set 9. There's a bunch of UI changes and there's also a few captures we should include over time. These should be enough to get officially started botting in Set 9 though.

### CODE REVIEW

**Review by Kyrluckechuck — APPROVED** [review]
Looks great, thanks for getting this up!
I've been a bit inactive (since I'm not using the bot these days with the high(er) ban rate), but these changes look about right and the QoL changes included look great (regarding the set changes, too)!

**Comment by akshualy** [comment]
> I've been a bit inactive (since I'm not using the bot these days with the high(er) ban rate)

Yeah, I've been continuously using it from source on an alt and it seems to still be fine. I'm pretty sure the `.exe` had something that tripped up League's AntiCheat.

**Comment by Kyrluckechuck** [comment]
> Yeah, I've been continuously using it from source on an alt and it seems to still be fine. I'm pretty sure the `.exe` had something that tripped up League's AntiCheat.

Ah interesting to hear! I wonder if it's worth starting to use it more often / not on alt's again 🤔

**Comment by akshualy** [comment]
I'm very tempted to use it on my main, the normal tft pass rewards look great, but I'm just way too lazy to farm it myself lol.
I'll develop the bot features that are still left to do on my main and will see how it goes.

**Pull request merged**
